import { useEffect, useState } from "react";

import {
  getRunStatus,
  onRunEvents,
  startRun,
  stopRun,
} from "../api";

interface ExternalRunnerPromptCardProps {
  /** The runner-agnostic prompt text generated by `preview_context`. */
  prompt: string;
  /** Placeholders like `<foo>` / `{foo}` that survived materialization, if
   *  any. Shown as a visible warning chip when non-empty. */
  unresolvedPlaceholders: string[];
  /** Vault root for the active scan. Passed straight to `start_run`. */
  vaultRoot: string;
  /** The selected project + prompt the card is currently previewing. */
  projectSlug: string;
  promptId: string;
}

/**
 * Primary export of a Run Plan: a runner-agnostic prompt the user can copy
 * into an external AI coding agent (Zed Agent, Claude Code, Codex, …) OR
 * run directly via the bundled Claude Code subprocess.
 *
 * Card actions:
 *   - **Run** — spawns `claude -p "<prompt>" --add-dir <vault>` with the
 *     project repo as cwd. Output streams in the bottom Run panel. Disabled
 *     while a run is already active.
 *   - **Copy** — writes `prompt` to clipboard for paste into another agent.
 *   - **Preview** — toggles a `<pre>` view of the same text.
 *   - **Runtime input** — optional free-text appended to the prompt as
 *     `## Additional input` (PR number, CVE id, question, etc.).
 */
export function ExternalRunnerPromptCard({
  prompt,
  unresolvedPlaceholders,
  vaultRoot,
  projectSlug,
  promptId,
}: ExternalRunnerPromptCardProps) {
  const [showPreview, setShowPreview] = useState(false);
  const [copyHint, setCopyHint] = useState<string | null>(null);
  const [runtimeInput, setRuntimeInput] = useState("");
  const [running, setRunning] = useState(false);
  const [runError, setRunError] = useState<string | null>(null);

  // Track whether a run is active so the Run button can disable itself.
  // The RunPanel subscribes too — multiple subscribers are fine, each
  // gets its own copy of every event. On mount we also query the backend
  // for the current state so a remount during an active run shows the
  // Stop button instead of an enabled Run.
  useEffect(() => {
    let detach: (() => void) | null = null;
    let cancelled = false;

    const attach = async () => {
      try {
        const snapshot = await getRunStatus();
        if (cancelled) return;
        setRunning(snapshot.active);
      } catch {
        // Best-effort; events alone will recover.
      }

      const un = await onRunEvents({
        onStarted: () => setRunning(true),
        onExit: () => setRunning(false),
      });
      if (cancelled) {
        un();
      } else {
        detach = un;
      }
    };

    attach().catch((err) => {
      if (cancelled) return;
      const text = err instanceof Error ? err.message : String(err);
      setRunError(`failed to attach run listeners: ${text}`);
    });

    return () => {
      cancelled = true;
      if (detach) detach();
    };
  }, []);

  const flashHint = (text: string): void => {
    setCopyHint(text);
    window.setTimeout(() => setCopyHint(null), 2500);
  };

  const onCopy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(prompt);
      flashHint("Copied to clipboard");
    } catch (err: unknown) {
      flashHint(
        `Copy failed: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  };

  const onRun = async (): Promise<void> => {
    setRunError(null);
    try {
      await startRun({
        vaultRoot,
        projectSlug,
        promptId,
        runtimeInput: runtimeInput.trim() === "" ? undefined : runtimeInput,
      });
      // `run:started` event will flip `running` to true.
    } catch (err) {
      setRunError(err instanceof Error ? err.message : String(err));
    }
  };

  const onStop = async (): Promise<void> => {
    try {
      await stopRun();
      // The `run:exit` event flips `running` to false. Don't preemptively
      // clear it here — the subprocess might take a moment to actually
      // terminate.
    } catch (err) {
      setRunError(err instanceof Error ? err.message : String(err));
      // If the stop call itself failed (e.g. backend mutex poison), we
      // don't know whether the run is alive or dead. Re-querying gives
      // us a fresh snapshot and prevents the button getting stuck on
      // "Stop" with a stale `running=true` indefinitely.
      try {
        const snapshot = await getRunStatus();
        setRunning(snapshot.active);
      } catch {
        // Both calls failed — leave state alone. The user can refresh.
      }
    }
  };

  return (
    <section
      className="preview__runner-prompt"
      aria-label="External runner prompt"
    >
      <header className="preview__section-header">
        <h4 className="preview__section-title">External Runner Prompt</h4>
        <div className="preview__controls">
          {running ? (
            <button
              type="button"
              className="btn btn--small btn--danger"
              onClick={() => {
                void onStop();
              }}
            >
              Stop
            </button>
          ) : (
            <button
              type="button"
              className="btn btn--primary btn--small"
              onClick={() => {
                void onRun();
              }}
              title="Spawn the local `claude` CLI with this prompt. Output streams in the panel below."
            >
              Run
            </button>
          )}
          <button
            type="button"
            className="btn btn--small"
            onClick={() => {
              void onCopy();
            }}
            title="Copy prompt to paste into another agent (Zed, Codex, …)."
          >
            Copy
          </button>
          <button
            type="button"
            className="btn btn--small"
            onClick={() => setShowPreview((v) => !v)}
            aria-expanded={showPreview}
          >
            {showPreview ? "Hide preview" : "Preview"}
          </button>
        </div>
      </header>
      <p className="preview__hint">
        Runner-agnostic prompt. <strong>Run</strong> spawns the local
        <code> claude </code>
        CLI in the project repo with the vault added via <code>--add-dir</code>.
        <strong> Copy</strong> the prompt to paste into Zed Agent, Codex, or
        any other coding agent.
      </p>
      <label className="preview__runtime-input">
        <span className="preview__runtime-input-label">Runtime input</span>
        <input
          type="text"
          className="preview__runtime-input-field"
          value={runtimeInput}
          onChange={(e) => setRuntimeInput(e.target.value)}
          placeholder="optional: PR number, CVE id, question — appended as `## Additional input`"
          disabled={running}
        />
      </label>
      {unresolvedPlaceholders.length > 0 && (
        <p className="preview__hint preview__hint--warn">
          Unresolved placeholders in the workflow body:
          {unresolvedPlaceholders.map((p) => (
            <code key={p} className="tag tag--warning">
              {p}
            </code>
          ))}
        </p>
      )}
      {runError && (
        <p className="welcome__error" role="alert">
          {runError}
        </p>
      )}
      {copyHint && (
        <p className="package-result__copy-hint" role="status">
          {copyHint}
        </p>
      )}
      {showPreview && (
        <pre
          className="preview__runner-prompt-text"
          aria-label="Generated runner prompt"
        >
          {prompt}
        </pre>
      )}
    </section>
  );
}
