import { useState } from "react";

interface ExternalRunnerPromptCardProps {
  /** The runner-agnostic prompt text generated by `preview_context`. */
  prompt: string;
  /** Placeholders like `<foo>` / `{foo}` that survived materialization, if
   *  any. Shown as a visible warning chip when non-empty. */
  unresolvedPlaceholders: string[];
}

/**
 * Primary export of a Run Plan: a short prompt the user copies into their
 * external AI coding agent (Zed Agent, Claude Code, Codex, Cursor, …).
 *
 * The card has two actions:
 *   - **Copy** — writes `prompt` to the clipboard, surfaces success/failure
 *   - **Preview** — toggles a `<pre>` view of the same text so the user can
 *     skim it before pasting
 *
 * This replaces the slice-10 "Generate Prompt Package" flow as the primary
 * external-runner handoff. No embedded vault/project files — the agent reads
 * paths from the prompt and asks the user for access when needed.
 */
export function ExternalRunnerPromptCard({
  prompt,
  unresolvedPlaceholders,
}: ExternalRunnerPromptCardProps) {
  const [showPreview, setShowPreview] = useState(false);
  const [copyHint, setCopyHint] = useState<string | null>(null);

  const flashHint = (text: string): void => {
    setCopyHint(text);
    window.setTimeout(() => setCopyHint(null), 2500);
  };

  const onCopy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(prompt);
      flashHint("Copied to clipboard");
    } catch (err: unknown) {
      flashHint(
        `Copy failed: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  };

  return (
    <section
      className="preview__runner-prompt"
      aria-label="External runner prompt"
    >
      <header className="preview__section-header">
        <h4 className="preview__section-title">External Runner Prompt</h4>
        <div className="preview__controls">
          <button
            type="button"
            className="btn btn--primary btn--small"
            onClick={() => {
              void onCopy();
            }}
          >
            Copy
          </button>
          <button
            type="button"
            className="btn btn--small"
            onClick={() => setShowPreview((v) => !v)}
            aria-expanded={showPreview}
          >
            {showPreview ? "Hide preview" : "Preview"}
          </button>
        </div>
      </header>
      <p className="preview__hint">
        Short, runner-agnostic prompt. Paste it into your AI coding agent
        (Zed Agent, Claude Code, Codex, Cursor, …). The agent reads vault
        rules and project context from disk paths in the prompt, asks for
        missing access, and returns proposed Markdown — no AI is called from
        the IDE.
      </p>
      {unresolvedPlaceholders.length > 0 && (
        <p className="preview__hint preview__hint--warn">
          Unresolved placeholders in the workflow body:
          {unresolvedPlaceholders.map((p) => (
            <code key={p} className="tag tag--warning">
              {p}
            </code>
          ))}
        </p>
      )}
      {copyHint && (
        <p className="package-result__copy-hint" role="status">
          {copyHint}
        </p>
      )}
      {showPreview && (
        <pre
          className="preview__runner-prompt-text"
          aria-label="Generated runner prompt"
        >
          {prompt}
        </pre>
      )}
    </section>
  );
}
