import { useState } from "react";

interface ExternalRunnerPromptCardProps {
  /** The runner-agnostic prompt text generated by `preview_context`. */
  prompt: string;
  /** Placeholders like `<foo>` / `{foo}` that survived materialization, if
   *  any. Shown as a visible warning chip when non-empty. */
  unresolvedPlaceholders: string[];
  /** The selected project + prompt the card is currently previewing. */
  projectSlug: string;
  promptId: string;
  /** Stage the prompt as a chat draft in the bottom panel. Called instead
   *  of spawning the runner directly so the user can edit, add additional
   *  context, or pre-approve permissions before sending. Returns `null`
   *  on success or an error string the card surfaces inline. */
  onStagePrompt: (args: {
    text: string;
    projectSlug: string;
    promptId: string;
  }) => string | null;
}

/**
 * Primary export of a Run Plan: a runner-agnostic prompt the user can copy
 * into an external AI coding agent (Zed Agent, Claude Code, Codex, …) OR
 * stage into the bundled chat panel to send via Claude Code.
 *
 * Card actions:
 *   - **Open in chat** — stages the prompt as a draft in the bottom Run
 *     panel, expands the panel, and focuses the textarea. The user reviews,
 *     can add runtime input or extra context, and presses Send to actually
 *     spawn `claude`. This replaces the older "Run immediately" behaviour
 *     so first-turn permission prompts can be pre-approved.
 *   - **Copy** — writes `prompt` to clipboard for paste into another agent.
 *   - **Preview** — toggles a `<pre>` view of the same text.
 *   - **Runtime input** — optional free-text appended to the prompt as
 *     `## Additional input` (PR number, CVE id, question, etc.).
 */
export function ExternalRunnerPromptCard({
  prompt,
  unresolvedPlaceholders,
  projectSlug,
  promptId,
  onStagePrompt,
}: ExternalRunnerPromptCardProps) {
  const [showPreview, setShowPreview] = useState(false);
  const [copyHint, setCopyHint] = useState<string | null>(null);
  const [runtimeInput, setRuntimeInput] = useState("");
  const [stageError, setStageError] = useState<string | null>(null);

  const flashHint = (text: string): void => {
    setCopyHint(text);
    window.setTimeout(() => setCopyHint(null), 2500);
  };

  /** Compose the staged draft text. Mirrors the backend's `runtime_input`
   *  handling in `build_stdin_messages` so the chat panel sends the same
   *  payload the runner would have built itself when started directly. */
  const composeStagedText = (): string => {
    const extra = runtimeInput.trim();
    if (extra === "") return prompt;
    return `${prompt}\n\n## Additional input\n\n${extra}\n`;
  };

  const onOpenInChat = (): void => {
    setStageError(null);
    const err = onStagePrompt({
      text: composeStagedText(),
      projectSlug,
      promptId,
    });
    if (err) setStageError(err);
  };

  const onCopy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(prompt);
      flashHint("Copied to clipboard");
    } catch (err: unknown) {
      flashHint(
        `Copy failed: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  };

  return (
    <section
      className="preview__runner-prompt"
      aria-label="External runner prompt"
    >
      <div className="preview__controls">
        <button
          type="button"
          className="btn btn--primary btn--small"
          onClick={onOpenInChat}
          title="Stage this prompt as a chat draft so you can review, add context, or pre-approve tool permissions before sending."
        >
          Open in chat
        </button>
        <button
          type="button"
          className="btn btn--small"
          onClick={() => {
            void onCopy();
          }}
          title="Copy prompt to paste into another agent (Zed, Codex, …)."
        >
          Copy
        </button>
        <button
          type="button"
          className="btn btn--small"
          onClick={() => setShowPreview((v) => !v)}
          aria-expanded={showPreview}
        >
          {showPreview ? "Hide preview" : "Preview"}
        </button>
      </div>
      <p className="preview__hint">
        <strong>Open in chat</strong> stages the prompt in the bottom panel —
        edit it, attach context, then Send when ready. Copy exports it for
        paste into another agent.
      </p>
      <label className="preview__runtime-input">
        <span className="preview__runtime-input-label">Runtime input</span>
        <input
          type="text"
          className="preview__runtime-input-field"
          value={runtimeInput}
          onChange={(e) => setRuntimeInput(e.target.value)}
          placeholder="optional: PR number, CVE id, question — appended as `## Additional input`"
        />
      </label>
      {unresolvedPlaceholders.length > 0 && (
        <p className="preview__hint preview__hint--warn">
          Unresolved placeholders in the workflow body:
          {unresolvedPlaceholders.map((p) => (
            <code key={p} className="tag tag--warning">
              {p}
            </code>
          ))}
        </p>
      )}
      {stageError && (
        <p className="welcome__error" role="alert">
          {stageError}
        </p>
      )}
      {copyHint && (
        <p className="package-result__copy-hint" role="status">
          {copyHint}
        </p>
      )}
      {showPreview && (
        <pre
          className="preview__runner-prompt-text"
          aria-label="Generated runner prompt"
        >
          {prompt}
        </pre>
      )}
    </section>
  );
}
